version: '3.8'

services:
  db:
    image: mysql:5.7
    container_name: mybookie_backend-db-1
    restart: always
    environment:
      MYSQL_DATABASE: mybookie
      MYSQL_USER: skugge
      MYSQL_PASSWORD: GhostChaser8
      MYSQL_ROOT_PASSWORD: GhostChaser8
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

  web:
    build: .
    container_name: mybookie_backend-web-1
    restart: always
    depends_on:
      - db
    environment:
      DATABASE_URL: mysql+pymysql://skugge:GhostChaser8@db/mybookie
    expose:
      - "8000"
    ports:
      - "8000:8000"
    volumes:
      - .:/app  

  nginx:
    image: nginx:latest
    container_name: mybookie_backend-nginx-1
    restart: always
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - web

volumes:
  db_data:
